// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multiview_consensus_protocol.proto

package com.pbft.multiview.core.grpc;

public interface GPongMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:multiview.GPongMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 error = 1;</code>
   * @return The error.
   */
  int getError();

  /**
   * <code>int32 nodeId = 2;</code>
   * @return The nodeId.
   */
  int getNodeId();
}
