// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multiview_consensus_protocol.proto

package com.pbft.multiview.core.grpc;

public interface GProposeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:multiview.GProposeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nodeId = 1;</code>
   * @return The nodeId.
   */
  int getNodeId();

  /**
   * <code>int32 height = 2;</code>
   * @return The height.
   */
  int getHeight();

  /**
   * <code>int32 round = 3;</code>
   * @return The round.
   */
  int getRound();

  /**
   * <code>int32 validRound = 4;</code>
   * @return The validRound.
   */
  int getValidRound();

  /**
   * <code>.multiview.GData data = 5;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.multiview.GData data = 5;</code>
   * @return The data.
   */
  com.pbft.multiview.core.grpc.GData getData();
  /**
   * <code>.multiview.GData data = 5;</code>
   */
  com.pbft.multiview.core.grpc.GDataOrBuilder getDataOrBuilder();

  /**
   * <code>bytes hashValue = 6;</code>
   * @return The hashValue.
   */
  com.google.protobuf.ByteString getHashValue();

  /**
   * <code>bytes signature = 7;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
