// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multiview_consensus_protocol.proto

package com.pbft.multiview.core.grpc;

public interface GRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:multiview.GRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();
}
