// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multiview_consensus_protocol.proto

package com.pbft.multiview.core.grpc;

public interface GResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:multiview.GResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 error = 1;</code>
   * @return The error.
   */
  int getError();

  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
