// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multiview_consensus_protocol.proto

package com.pbft.multiview.core.grpc;

public final class MultiviewConsensusProto {
  private MultiviewConsensusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multiview_GPingMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multiview_GPingMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multiview_GPongMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multiview_GPongMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multiview_GData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multiview_GData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multiview_GProposeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multiview_GProposeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multiview_GVoteMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multiview_GVoteMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multiview_GResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multiview_GResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multiview_GRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multiview_GRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"multiview_consensus_protocol.proto\022\tmu" +
      "ltiview\"\036\n\014GPingMessage\022\016\n\006nodeId\030\001 \001(\005\"" +
      "-\n\014GPongMessage\022\r\n\005error\030\001 \001(\005\022\016\n\006nodeId" +
      "\030\002 \001(\005\")\n\005GData\022\021\n\ttimestamp\030\001 \001(\004\022\r\n\005va" +
      "lue\030\002 \001(\t\"\232\001\n\017GProposeMessage\022\016\n\006nodeId\030" +
      "\001 \001(\005\022\016\n\006height\030\002 \001(\005\022\r\n\005round\030\003 \001(\005\022\022\n\n" +
      "validRound\030\004 \001(\005\022\036\n\004data\030\005 \001(\0132\020.multivi" +
      "ew.GData\022\021\n\thashValue\030\006 \001(\014\022\021\n\tsignature" +
      "\030\007 \001(\014\"c\n\014GVoteMessage\022\016\n\006height\030\001 \001(\005\022\r" +
      "\n\005round\030\002 \001(\005\022\021\n\thashValue\030\003 \001(\014\022\021\n\tsign" +
      "ature\030\004 \001(\014\022\016\n\006nodeId\030\005 \001(\005\"&\n\007GResult\022\r" +
      "\n\005error\030\001 \001(\005\022\014\n\004data\030\002 \001(\t\"\032\n\010GRequest\022" +
      "\016\n\006status\030\001 \001(\0052\232\002\n\031GConsensusProtocolSe" +
      "rvice\022:\n\004Ping\022\027.multiview.GPingMessage\032\027" +
      ".multiview.GPongMessage\"\000\022D\n\020OnProposeMe" +
      "ssage\022\032.multiview.GProposeMessage\032\022.mult" +
      "iview.GResult\"\000\022>\n\rOnVoteMessage\022\027.multi" +
      "view.GVoteMessage\032\022.multiview.GResult\"\000\022" +
      ";\n\016StartConsensus\022\023.multiview.GRequest\032\022" +
      ".multiview.GResult\"\000B9\n\034com.pbft.multivi" +
      "ew.core.grpcB\027MultiviewConsensusProtoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_multiview_GPingMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_multiview_GPingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multiview_GPingMessage_descriptor,
        new java.lang.String[] { "NodeId", });
    internal_static_multiview_GPongMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_multiview_GPongMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multiview_GPongMessage_descriptor,
        new java.lang.String[] { "Error", "NodeId", });
    internal_static_multiview_GData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_multiview_GData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multiview_GData_descriptor,
        new java.lang.String[] { "Timestamp", "Value", });
    internal_static_multiview_GProposeMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_multiview_GProposeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multiview_GProposeMessage_descriptor,
        new java.lang.String[] { "NodeId", "Height", "Round", "ValidRound", "Data", "HashValue", "Signature", });
    internal_static_multiview_GVoteMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_multiview_GVoteMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multiview_GVoteMessage_descriptor,
        new java.lang.String[] { "Height", "Round", "HashValue", "Signature", "NodeId", });
    internal_static_multiview_GResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_multiview_GResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multiview_GResult_descriptor,
        new java.lang.String[] { "Error", "Data", });
    internal_static_multiview_GRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_multiview_GRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multiview_GRequest_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
