// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint_consensus_protocol.proto

package com.pbft.tendermint.core.grpc;

public interface GPingMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tendermint.GPingMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nodeId = 1;</code>
   * @return The nodeId.
   */
  int getNodeId();
}
