// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint_consensus_protocol.proto

package com.pbft.tendermint.core.grpc;

/**
 * Protobuf type {@code tendermint.GProposeMessage}
 */
public final class GProposeMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tendermint.GProposeMessage)
    GProposeMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GProposeMessage.newBuilder() to construct.
  private GProposeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GProposeMessage() {
    hashValue_ = com.google.protobuf.ByteString.EMPTY;
    signature_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GProposeMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GProposeMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            nodeId_ = input.readInt32();
            break;
          }
          case 16: {

            height_ = input.readInt32();
            break;
          }
          case 24: {

            round_ = input.readInt32();
            break;
          }
          case 32: {

            validRound_ = input.readInt32();
            break;
          }
          case 42: {
            com.pbft.tendermint.core.grpc.GData.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(com.pbft.tendermint.core.grpc.GData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {

            hashValue_ = input.readBytes();
            break;
          }
          case 58: {

            signature_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pbft.tendermint.core.grpc.TendermintConsensusProto.internal_static_tendermint_GProposeMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pbft.tendermint.core.grpc.TendermintConsensusProto.internal_static_tendermint_GProposeMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pbft.tendermint.core.grpc.GProposeMessage.class, com.pbft.tendermint.core.grpc.GProposeMessage.Builder.class);
  }

  public static final int NODEID_FIELD_NUMBER = 1;
  private int nodeId_;
  /**
   * <code>int32 nodeId = 1;</code>
   * @return The nodeId.
   */
  @java.lang.Override
  public int getNodeId() {
    return nodeId_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 2;
  private int height_;
  /**
   * <code>int32 height = 2;</code>
   * @return The height.
   */
  @java.lang.Override
  public int getHeight() {
    return height_;
  }

  public static final int ROUND_FIELD_NUMBER = 3;
  private int round_;
  /**
   * <code>int32 round = 3;</code>
   * @return The round.
   */
  @java.lang.Override
  public int getRound() {
    return round_;
  }

  public static final int VALIDROUND_FIELD_NUMBER = 4;
  private int validRound_;
  /**
   * <code>int32 validRound = 4;</code>
   * @return The validRound.
   */
  @java.lang.Override
  public int getValidRound() {
    return validRound_;
  }

  public static final int DATA_FIELD_NUMBER = 5;
  private com.pbft.tendermint.core.grpc.GData data_;
  /**
   * <code>.tendermint.GData data = 5;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.tendermint.GData data = 5;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.pbft.tendermint.core.grpc.GData getData() {
    return data_ == null ? com.pbft.tendermint.core.grpc.GData.getDefaultInstance() : data_;
  }
  /**
   * <code>.tendermint.GData data = 5;</code>
   */
  @java.lang.Override
  public com.pbft.tendermint.core.grpc.GDataOrBuilder getDataOrBuilder() {
    return getData();
  }

  public static final int HASHVALUE_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString hashValue_;
  /**
   * <code>bytes hashValue = 6;</code>
   * @return The hashValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getHashValue() {
    return hashValue_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString signature_;
  /**
   * <code>bytes signature = 7;</code>
   * @return The signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nodeId_ != 0) {
      output.writeInt32(1, nodeId_);
    }
    if (height_ != 0) {
      output.writeInt32(2, height_);
    }
    if (round_ != 0) {
      output.writeInt32(3, round_);
    }
    if (validRound_ != 0) {
      output.writeInt32(4, validRound_);
    }
    if (data_ != null) {
      output.writeMessage(5, getData());
    }
    if (!hashValue_.isEmpty()) {
      output.writeBytes(6, hashValue_);
    }
    if (!signature_.isEmpty()) {
      output.writeBytes(7, signature_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nodeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, nodeId_);
    }
    if (height_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, height_);
    }
    if (round_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, round_);
    }
    if (validRound_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, validRound_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getData());
    }
    if (!hashValue_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, hashValue_);
    }
    if (!signature_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, signature_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pbft.tendermint.core.grpc.GProposeMessage)) {
      return super.equals(obj);
    }
    com.pbft.tendermint.core.grpc.GProposeMessage other = (com.pbft.tendermint.core.grpc.GProposeMessage) obj;

    if (getNodeId()
        != other.getNodeId()) return false;
    if (getHeight()
        != other.getHeight()) return false;
    if (getRound()
        != other.getRound()) return false;
    if (getValidRound()
        != other.getValidRound()) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!getHashValue()
        .equals(other.getHashValue())) return false;
    if (!getSignature()
        .equals(other.getSignature())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODEID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getHeight();
    hash = (37 * hash) + ROUND_FIELD_NUMBER;
    hash = (53 * hash) + getRound();
    hash = (37 * hash) + VALIDROUND_FIELD_NUMBER;
    hash = (53 * hash) + getValidRound();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (37 * hash) + HASHVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getHashValue().hashCode();
    hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getSignature().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pbft.tendermint.core.grpc.GProposeMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pbft.tendermint.core.grpc.GProposeMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pbft.tendermint.core.grpc.GProposeMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tendermint.GProposeMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tendermint.GProposeMessage)
      com.pbft.tendermint.core.grpc.GProposeMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pbft.tendermint.core.grpc.TendermintConsensusProto.internal_static_tendermint_GProposeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pbft.tendermint.core.grpc.TendermintConsensusProto.internal_static_tendermint_GProposeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pbft.tendermint.core.grpc.GProposeMessage.class, com.pbft.tendermint.core.grpc.GProposeMessage.Builder.class);
    }

    // Construct using com.pbft.tendermint.core.grpc.GProposeMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nodeId_ = 0;

      height_ = 0;

      round_ = 0;

      validRound_ = 0;

      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      hashValue_ = com.google.protobuf.ByteString.EMPTY;

      signature_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pbft.tendermint.core.grpc.TendermintConsensusProto.internal_static_tendermint_GProposeMessage_descriptor;
    }

    @java.lang.Override
    public com.pbft.tendermint.core.grpc.GProposeMessage getDefaultInstanceForType() {
      return com.pbft.tendermint.core.grpc.GProposeMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.pbft.tendermint.core.grpc.GProposeMessage build() {
      com.pbft.tendermint.core.grpc.GProposeMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pbft.tendermint.core.grpc.GProposeMessage buildPartial() {
      com.pbft.tendermint.core.grpc.GProposeMessage result = new com.pbft.tendermint.core.grpc.GProposeMessage(this);
      result.nodeId_ = nodeId_;
      result.height_ = height_;
      result.round_ = round_;
      result.validRound_ = validRound_;
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      result.hashValue_ = hashValue_;
      result.signature_ = signature_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pbft.tendermint.core.grpc.GProposeMessage) {
        return mergeFrom((com.pbft.tendermint.core.grpc.GProposeMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pbft.tendermint.core.grpc.GProposeMessage other) {
      if (other == com.pbft.tendermint.core.grpc.GProposeMessage.getDefaultInstance()) return this;
      if (other.getNodeId() != 0) {
        setNodeId(other.getNodeId());
      }
      if (other.getHeight() != 0) {
        setHeight(other.getHeight());
      }
      if (other.getRound() != 0) {
        setRound(other.getRound());
      }
      if (other.getValidRound() != 0) {
        setValidRound(other.getValidRound());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      if (other.getHashValue() != com.google.protobuf.ByteString.EMPTY) {
        setHashValue(other.getHashValue());
      }
      if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
        setSignature(other.getSignature());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pbft.tendermint.core.grpc.GProposeMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pbft.tendermint.core.grpc.GProposeMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int nodeId_ ;
    /**
     * <code>int32 nodeId = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public int getNodeId() {
      return nodeId_;
    }
    /**
     * <code>int32 nodeId = 1;</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(int value) {
      
      nodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nodeId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      
      nodeId_ = 0;
      onChanged();
      return this;
    }

    private int height_ ;
    /**
     * <code>int32 height = 2;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }
    /**
     * <code>int32 height = 2;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(int value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 height = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      
      height_ = 0;
      onChanged();
      return this;
    }

    private int round_ ;
    /**
     * <code>int32 round = 3;</code>
     * @return The round.
     */
    @java.lang.Override
    public int getRound() {
      return round_;
    }
    /**
     * <code>int32 round = 3;</code>
     * @param value The round to set.
     * @return This builder for chaining.
     */
    public Builder setRound(int value) {
      
      round_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 round = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRound() {
      
      round_ = 0;
      onChanged();
      return this;
    }

    private int validRound_ ;
    /**
     * <code>int32 validRound = 4;</code>
     * @return The validRound.
     */
    @java.lang.Override
    public int getValidRound() {
      return validRound_;
    }
    /**
     * <code>int32 validRound = 4;</code>
     * @param value The validRound to set.
     * @return This builder for chaining.
     */
    public Builder setValidRound(int value) {
      
      validRound_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 validRound = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidRound() {
      
      validRound_ = 0;
      onChanged();
      return this;
    }

    private com.pbft.tendermint.core.grpc.GData data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.pbft.tendermint.core.grpc.GData, com.pbft.tendermint.core.grpc.GData.Builder, com.pbft.tendermint.core.grpc.GDataOrBuilder> dataBuilder_;
    /**
     * <code>.tendermint.GData data = 5;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <code>.tendermint.GData data = 5;</code>
     * @return The data.
     */
    public com.pbft.tendermint.core.grpc.GData getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.pbft.tendermint.core.grpc.GData.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.tendermint.GData data = 5;</code>
     */
    public Builder setData(com.pbft.tendermint.core.grpc.GData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.tendermint.GData data = 5;</code>
     */
    public Builder setData(
        com.pbft.tendermint.core.grpc.GData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.tendermint.GData data = 5;</code>
     */
    public Builder mergeData(com.pbft.tendermint.core.grpc.GData value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            com.pbft.tendermint.core.grpc.GData.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.tendermint.GData data = 5;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.tendermint.GData data = 5;</code>
     */
    public com.pbft.tendermint.core.grpc.GData.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.tendermint.GData data = 5;</code>
     */
    public com.pbft.tendermint.core.grpc.GDataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.pbft.tendermint.core.grpc.GData.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.tendermint.GData data = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.pbft.tendermint.core.grpc.GData, com.pbft.tendermint.core.grpc.GData.Builder, com.pbft.tendermint.core.grpc.GDataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.pbft.tendermint.core.grpc.GData, com.pbft.tendermint.core.grpc.GData.Builder, com.pbft.tendermint.core.grpc.GDataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private com.google.protobuf.ByteString hashValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes hashValue = 6;</code>
     * @return The hashValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHashValue() {
      return hashValue_;
    }
    /**
     * <code>bytes hashValue = 6;</code>
     * @param value The hashValue to set.
     * @return This builder for chaining.
     */
    public Builder setHashValue(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hashValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes hashValue = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearHashValue() {
      
      hashValue_ = getDefaultInstance().getHashValue();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes signature = 7;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <code>bytes signature = 7;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes signature = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tendermint.GProposeMessage)
  }

  // @@protoc_insertion_point(class_scope:tendermint.GProposeMessage)
  private static final com.pbft.tendermint.core.grpc.GProposeMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pbft.tendermint.core.grpc.GProposeMessage();
  }

  public static com.pbft.tendermint.core.grpc.GProposeMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GProposeMessage>
      PARSER = new com.google.protobuf.AbstractParser<GProposeMessage>() {
    @java.lang.Override
    public GProposeMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GProposeMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GProposeMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GProposeMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pbft.tendermint.core.grpc.GProposeMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

